// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-iroh.h"
#endif

#import <React/RCTBridgeModule.h>

#ifdef RCT_NEW_ARCH_ENABLED
#import <ReactCommon/RCTTurboModule.h>

@interface IrohBridge : NSObject <RCTBridgeModule, RCTTurboModule>
#else
@interface IrohBridge : NSObject <RCTBridgeModule>
#endif

@end
