---
rust:
  directory: ../rust/iroh_mobile_bridge
  manifestPath: Cargo.toml
android:
  packageName: design.gordo.musichub.iroh
  apiLevel: 24
  useSharedLibrary: true
ios:
  frameworkName: MusicHubIrohBridgeFramework
bindings:
  ts: src/generated
noOverwrite:
  - src/index.js
  - src/index.d.ts
