// Generated by uniffi-bindgen-react-native
package design.gordo.iroh.reactnative

import android.content.Context
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.module.annotations.ReactModule
import com.facebook.react.turbomodule.core.interfaces.CallInvokerHolder

@ReactModule(name = IrohBridgeModule.NAME)
class IrohBridgeModule(reactContext: ReactApplicationContext) :
  NativeIrohBridgeSpec(reactContext) {

  override fun getName(): String {
    return NAME
  }

  // Native methods implemented in cpp-adapter.cpp, and ultimately
  // react-native-iroh.cpp.

  external fun nativeInitAndroidContext(applicationContext: Context): Boolean
  external fun nativeInstallRustCrate(runtimePointer: Long, callInvoker: CallInvokerHolder): Boolean
  external fun nativeCleanupRustCrate(runtimePointer: Long): Boolean

  override fun installRustCrate(): Boolean {
    val context = this.reactApplicationContext
    if (!nativeInitAndroidContext(context.applicationContext)) {
      return false
    }
    return nativeInstallRustCrate(
      context.javaScriptContextHolder!!.get(),
      context.jsCallInvokerHolder!!
    )
  }

  override fun cleanupRustCrate(): Boolean {
    return nativeCleanupRustCrate(
      this.reactApplicationContext.javaScriptContextHolder!!.get()
    )
  }

  companion object {
    const val NAME = "IrohBridge"

    init {
      System.loadLibrary("react-native-iroh")
    }
  }
}
