// Generated by uniffi-bindgen-react-native
#include <jni.h>
#include <jsi/jsi.h>
#include <ReactCommon/CallInvokerHolder.h>
#include "music-hub-iroh-bridge.h"

namespace jsi = facebook::jsi;
namespace react = facebook::react;

// Automated testing checks Java_design_gordo_musichub_iroh_IrohBridgeModule and musichub_irohbridge
// by comparing the whole line here.
/*
Java_design_gordo_musichub_iroh_IrohBridgeModule_nativeMultiply(JNIEnv *env, jclass type, jdouble a, jdouble b) {
    return musichub_irohbridge::multiply(a, b);
}
*/

// Installer coming from IrohBridgeModule
extern "C"
JNIEXPORT jboolean JNICALL
Java_design_gordo_musichub_iroh_IrohBridgeModule_nativeInstallRustCrate(
    JNIEnv *env,
    jclass type,
    jlong rtPtr,
    jobject callInvokerHolderJavaObj
) {
    using JCallInvokerHolder = facebook::react::CallInvokerHolder;

    auto holderLocal = facebook::jni::make_local(callInvokerHolderJavaObj);
    auto holderRef = facebook::jni::static_ref_cast<JCallInvokerHolder::javaobject>(holderLocal);
    auto* holderCxx = holderRef->cthis();
    auto jsCallInvoker = holderCxx->getCallInvoker();
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);

    return musichub_irohbridge::installRustCrate(*runtime, jsCallInvoker);
}

extern "C"
JNIEXPORT jboolean JNICALL
Java_design_gordo_musichub_iroh_IrohBridgeModule_nativeCleanupRustCrate(JNIEnv *env, jclass type, jlong rtPtr) {
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);
    return musichub_irohbridge::cleanupRustCrate(*runtime);
}