// Generated by uniffi-bindgen-react-native, with Iroh Android context wiring.
#include <jni.h>
#include <jsi/jsi.h>
#include <ReactCommon/CallInvokerHolder.h>
#include "react-native-iroh.h"

namespace jsi = facebook::jsi;
namespace react = facebook::react;

static jboolean initAndroidContext(
    JNIEnv *env,
    jobject applicationContext
) {
    JavaVM *javaVm = nullptr;
    if (env->GetJavaVM(&javaVm) != JNI_OK || javaVm == nullptr || applicationContext == nullptr) {
        return false;
    }

    jobject globalContext = env->NewGlobalRef(applicationContext);
    if (globalContext == nullptr) {
        return false;
    }

    uint8_t initialized = reactnativeiroh::initAndroidContext(
        reinterpret_cast<void *>(javaVm),
        reinterpret_cast<void *>(globalContext)
    );
    if (!initialized) {
        env->DeleteGlobalRef(globalContext);
    }
    return initialized != 0;
}

static jboolean installRustCrate(
    JNIEnv *env,
    jlong rtPtr,
    jobject callInvokerHolderJavaObj
) {
    using JCallInvokerHolder = facebook::react::CallInvokerHolder;

    auto holderLocal = facebook::jni::make_local(callInvokerHolderJavaObj);
    auto holderRef = facebook::jni::static_ref_cast<JCallInvokerHolder::javaobject>(holderLocal);
    auto* holderCxx = holderRef->cthis();
    auto jsCallInvoker = holderCxx->getCallInvoker();
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);

    return reactnativeiroh::installRustCrate(*runtime, jsCallInvoker);
}

static jboolean cleanupRustCrate(jlong rtPtr) {
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);
    return reactnativeiroh::cleanupRustCrate(*runtime);
}

extern "C"
JNIEXPORT jboolean JNICALL
Java_design_gordo_iroh_reactnative_IrohBridgeModule_nativeInitAndroidContext(
    JNIEnv *env,
    jobject type,
    jobject applicationContext
) {
    return initAndroidContext(env, applicationContext);
}

extern "C"
JNIEXPORT jboolean JNICALL
Java_design_gordo_iroh_reactnative_IrohBridgeModule_nativeInstallRustCrate(
    JNIEnv *env,
    jclass type,
    jlong rtPtr,
    jobject callInvokerHolderJavaObj
) {
    return installRustCrate(env, rtPtr, callInvokerHolderJavaObj);
}

extern "C"
JNIEXPORT jboolean JNICALL
Java_design_gordo_iroh_reactnative_IrohBridgeModule_nativeCleanupRustCrate(
    JNIEnv *env,
    jclass type,
    jlong rtPtr
) {
    return cleanupRustCrate(rtPtr);
}
