#ifndef MUSICHUB_IROHBRIDGE_H
#define MUSICHUB_IROHBRIDGE_H
// Generated by uniffi-bindgen-react-native
#include <cstdint>
#include <jsi/jsi.h>
#include <ReactCommon/CallInvoker.h>

namespace musichub_irohbridge {
  using namespace facebook;

  uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker);
  uint8_t cleanupRustCrate(jsi::Runtime &runtime);
}

#endif /* MUSICHUB_IROHBRIDGE_H */
