// Generated by uniffi-bindgen-react-native
#include "music-hub-iroh-bridge.h"
#include "generated/iroh_mobile_bridge.hpp"

namespace musichub_irohbridge {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeIrohMobileBridge::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}
