// Generated by uniffi-bindgen-react-native
#include "react-native-iroh.h"
#include "generated/iroh_mobile_bridge.hpp"

#if defined(__ANDROID__)
extern "C" uint8_t react_native_iroh_init_android_context(void *javaVm, void *applicationContext);
#endif

namespace reactnativeiroh {
	using namespace facebook;

	uint8_t initAndroidContext(void *javaVm, void *applicationContext) {
#if defined(__ANDROID__)
		return react_native_iroh_init_android_context(javaVm, applicationContext);
#else
		(void)javaVm;
		(void)applicationContext;
		return 1;
#endif
	}

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeIrohMobileBridge::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}
